# Generated by Django 4.2.6 on 2023-10-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyecto_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
